/*
 * Root layout of the Scrabble application.
 *
 * This file defines the global HTML document structure
 * and wraps all application pages. It is responsible for
 * setting shared styles, fonts, and metadata that apply
 * to the entire application.
 */

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

/*
 * Definition of global fonts using Next.js font optimization.
 * Fonts are exposed as CSS variables and applied to the <body>.
 */
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

/*
 * Global application metadata (title, description).
 * Used for the HTML document head and search engine previews.
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/*
 * Root layout component.
 * The `children` prop represents the content of the currently rendered page.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
